
version: '3'
services:
  backend:
    image: dgksu/django-business-logic:demo
    platform: linux/amd64
    ports:
    - 8000:8000
  frontend:
    build:
      context: .

    command: "sh -c 'npm run start'"
    platform: linux/amd64
    ports:
    - 8080:8080